### ISSUE TITLE
node-waifupics

### ISSUE THREAD

**Issue by ruj** [tentaclenotsoft/node-waifupics#2]
It is suggested to change the repository name to **node-waifupics**, a better url search.
In the current name there is a slight problem of congnitation in the `.` (dot) because the `-` (hyphen) has already been printed before
Without the dot visually it also looks better

**Comment by samueldurantes** [comment]
Here it is https://github.com/tentaclenotsoft/node-waifupics/commit/481bc566948fb7a9c679c6cd709334931faa801d
I changed the keyword `waifu.api` to` waifu.pics` thus establishing a better relation to the site.
