### ISSUE TITLE
WaifuPics.fetch('lewdneko')

### ISSUE THREAD

**Issue by folliejester** [tentaclenotsoft/node-waifupics#3]
FetchError: invalid json response body at https://waifu.pics/api/lewdneko reason: Unexpected token E in JSON at position 0
    at C:\Users\7thghoul\Documents\Syden\node_modules\waifu.pics\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  type: 'invalid-json'
}

**Comment by ruj** [comment]
This is happening because this endpoint is not processing the request, maybe this will be resolved later in the api.
I sent a request to throw the failure to catch if it happens again. #4

**Comment by JSH32** [comment]
Lewdneko is currently empty, I'm adding images to it but if it has zero images it will simply return a 500 error, I will fix this.

**Comment by folliejester** [comment]
Can i help you guys as well? Create some more categories, like bobs, etc etc and create a cloud space where i can upload mine.

**Comment by JSH32** [comment]
yeah, I can add a boob category, ill do it tomorrow probably @7thghoul

**Comment by folliejester** [comment]
> yeah, I can add a boob category, ill do it tomorrow probably @7thghoul 

Tq.. you should use * though :3
Idk how strict is github

**Comment by JSH32** [comment]
hm?

**Comment by folliejester** [comment]
Thank you for adding lewdnekos❤️❤️❤️
